// <auto-generated />
namespace SimpleMVCBlog.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class createduseridarticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createduseridarticle));
        
        string IMigrationMetadata.Id
        {
            get { return "201408251648245_createduserid-article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
