// <auto-generated />
namespace SimpleMVCBlog.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updateusernamecomment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateusernamecomment));
        
        string IMigrationMetadata.Id
        {
            get { return "201408231643579_update-username-comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
